include: package:very_good_analysis/analysis_options.6.0.0.yaml
analyzer:
  errors:
    always_use_package_imports: ignore
    eol_at_end_of_file: ignore
    flutter_style_todos: ignore
    lines_longer_than_80_chars: ignore
    prefer_constructors_over_static_methods: ignore
    public_member_api_docs: ignore
    require_trailing_commas: ignore
    sort_constructors_first: ignore
    unnecessary_lambdas: ignore
    use_super_parameters: ignore
