name: simple_tracer
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
dependencies:
  fixnum: ^1.1.1
  grpc: ^4.0.4
  protobuf: ^4.0.0

