name: simple_tracer
description: Simple implementation of opentelemetry tracing for flutter and dart projects.

version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
dependencies:
  dio:
  fixnum: ^1.1.1
  grpc: ^4.0.4
  protobuf: ^4.0.0
  uuid: ^4.5.1

